let a = "hello";
console.log(a);
console.log(typeof a);
alert(a);
document.write(a);
let b = "owu";
console.log(b);
console.log(typeof b);
alert(b);
document.write(b);
let c = 'com';
console.log(c);
console.log(typeof c);
alert(c);
document.write(c);
let d = 'ua';
console.log(d);
console.log(typeof d);
alert(d);
document.write(d);
let f = 1;
console.log(f);
console.log(typeof f);
alert(f);
document.write(`f`);
let g = 10;
console.log(g);
console.log(typeof g);
alert(g);
document.write(g);
let h = -999;
console.log(h);
console.log(typeof h);
alert(h);
document.write(h);
let i = 123;
console.log(i);
console.log(typeof i);
alert(i);
document.write(i);
let j = 3.14;
console.log(j);
console.log(typeof j);
alert(j);
document.write(j);
let k = 2.7;
console.log(k);
console.log(typeof k);
alert(k);
document.write(k);
let l = 16;
console.log(l);
console.log(typeof l);
alert(l);
document.write(l);
let m = true;
console.log(m);
console.log(typeof m);
alert(m);
document.write(m);
let n = false;
console.log(n);
console.log(typeof n);
alert(n);
document.write(n);

let firstName = "Volodymyr";
let middleName = "Yuriyovych";
let lastName = "Khmura";
let person = firstName+''+middleName+''+lastName;
console.log(person);
let person1=`${firstName} ${middleName} ${lastName}`;
console.log(person1);

let A = 100;
let B = '100';
let C = true;
console.log(typeof A);
console.log(typeof B);
console.log(typeof C);

let name = prompt('Enter your name');
console.log(name);
let sname = prompt('Enter your second name');
console.log(sname);
let year = +prompt('Enter the year of your birth');
console.log(year);